# Generated by Django 5.2.4 on 2025-07-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name_urdu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_urdu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='full_name_urdu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
