# Generated by Django 5.2.4 on 2025-08-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_student_full_name_urdu_subject_name_urdu_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performanceentry',
            unique_together={('report', 'subject')},
        ),
    ]
