# Generated by Django 5.2.4 on 2025-09-09 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_backfill_exam_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=100, verbose_name='term'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', related_query_name='exam', to='reports.examsession'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', related_query_name='enrollment', to='reports.examsession'),
        ),
    ]
