# Generated by Django 5.2.4 on 2025-09-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_exam_date_alter_exam_name_alter_exam_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name_urdu',
            field=models.CharField(blank=True, db_column='full_name_urdu', max_length=100, null=True),
        ),
        migrations.RenameField(
            model_name='student',
            old_name='full_name_urdu',
            new_name='full_name_ur',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='full_name_urdu',
            new_name='full_name_ur',
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
