# Generated by Django 5.2.4 on 2025-09-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_student_full_name_urdu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('exam_type', models.CharField(max_length=50)),
                ('marks_obtained', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='reports.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='reports.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='reports.subject')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'session', 'term', 'exam_type'], name='reports_stu_student_461469_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'session', 'term', 'exam_type', 'subject'), name='uniq_mark_per_student_session_term_type_subject')],
            },
        ),
    ]
