# Generated by Django 5.2.4 on 2025-09-17 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_studentexammark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tutor',
            name='uniq_tutor_phone_when_present',
        ),
        migrations.AlterUniqueTogether(
            name='performanceentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='messagelog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name_ur',
        ),
        migrations.RemoveField(
            model_name='studentexammark',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentexammark',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='created_at',
        ),
        migrations.AddField(
            model_name='examsession',
            name='label',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name_urdu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Mid-Term', 'Mid-Term'), ('Final', 'Final'), ('Tests Week', 'Tests Week'), ('Monthly Test', 'Monthly Test'), ('Quiz', 'Quiz')], max_length=50),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='contact_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('WhatsApp', 'WhatsApp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentexammark',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.examsession'),
        ),
        migrations.AlterField(
            model_name='studentexammark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.student'),
        ),
        migrations.AlterField(
            model_name='studentexammark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.subject'),
        ),
        migrations.AlterField(
            model_name='studentexammark',
            name='term',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='studentexammark',
            index=models.Index(fields=['student', 'session'], name='reports_stu_student_b4d9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsession',
            index=models.Index(fields=['student', 'session'], name='reports_stu_student_a921d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='tutor',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False), models.Q(('phone', ''), _negated=True)), fields=('phone',), name='uniq_tutor_phone_nonnull'),
        ),
    ]
