# Generated by Django 5.2.4 on 2025-09-17 15:07
from django.db import migrations

def compute_label(name, year, start, end):
    if start:
        y1 = start.year
        y2 = end.year if end else (y1 + 1)
        return f"{y1}-{y2}"
    if year:
        return f"{year}-{year + 1}"
    if name:
        import re
        m = re.search(r'(20\d{2})\s*[-/]\s*(20\d{2})', name)
        if m: return f"{m.group(1)}-{m.group(2)}"
        m = re.search(r'(20\d{2})', name)
        if m: return f"{m.group(1)}-{int(m.group(1)) + 1}"
        return name.strip()
    return None

def forwards(apps, schema_editor):
    ExamSession = apps.get_model('reports', 'ExamSession')
    for s in ExamSession.objects.all():
        if not s.label:
            s.label = compute_label(s.name, s.year, s.start_date, s.end_date) or str(s.pk)
            s.save(update_fields=['label'])

class Migration(migrations.Migration):
    dependencies = [('reports', '0011_remove_tutor_uniq_tutor_phone_when_present_and_more')]
    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]

