# Generated by Django 5.2.4 on 2025-09-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_backfill_session_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='label',
        ),
    ]
