# Generated by Django 5.2.4 on 2025-09-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_remove_examsession_label'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', False)), fields=('year',), name='uniq_session_year_nonnull'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False), models.Q(('name', ''), _negated=True)), fields=('name',), name='uniq_session_name_nonnull_nonblank'),
        ),
    ]
