# Generated by Django 5.2.4 on 2025-09-30 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_new_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('weight_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gradeboundary',
            options={'ordering': ['-min_pct']},
        ),
        migrations.RemoveConstraint(
            model_name='examsession',
            name='uniq_session_year_nonnull',
        ),
        migrations.RemoveConstraint(
            model_name='examsession',
            name='uniq_session_name_nonnull_nonblank',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='reports_enr_student_12dd77_idx',
            old_name='reports_enr_student_ay_idx',
        ),
        migrations.RenameIndex(
            model_name='examevent',
            new_name='reports_exa_exam_id_530a50_idx',
            old_name='reports_exe_exam_section_idx',
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', False)), fields=('organization', 'year'), name='uniq_session_year_per_org_nonnull'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False), models.Q(('name', ''), _negated=True)), fields=('organization', 'name'), name='uniq_session_name_per_org_nonnull_nonblank'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.organization'),
        ),
    ]
