# Generated by Django 5.2.4 on 2025-10-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_messagetemplate_auditlog_guardian_messagethread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
